### ISSUE TITLE
 Enabling i2c0 on gpio 0 and 1

### ISSUE THREAD

**Issue by Bra1nsen** [pinout-xyz/Pinout.xyz#457]
Hey thanks for your pinout website - its amazing!!

Iam wondering, if theres a guidance for setting up the gpio pins 0 and 1 for I²C. 

![image](https://user-images.githubusercontent.com/58213050/222841972-7f3e56b9-693a-4a84-ae8a-7bd36e4f9432.png)

Any help/hint would be appreciated.

**Comment by lurch** [comment]
This is probably a question best asked at https://forums.raspberrypi.com/ ?

**Comment by Bra1nsen** [comment]
Iam interested in improving the pinout webside, wouldnt it be useful for the community to integrate a linke with a guidance for that topic? Kind regards

**Comment by lurch** [comment]
Ah, it wasn't clear that your initial comment was a suggestion rather than a question - apologies if my reply seems patronising in hindsight.

IMHO it's up to @Gadgetoid what he does or doesn't include on these pages :wink:

**Comment by ali1234** [comment]
I would say the current text is a bit out-of-date. Hardly anything uses ID eeproms but the firmware also uses this bus to control the DSI camera. If you take it over then you lose both those things, and camera is arguably the more important one.

**Comment by lurch** [comment]
> Hardly anything uses ID eeproms

Not sure that's accurate? Lot's of [HATs](https://www.raspberrypi.com/news/introducing-raspberry-pi-hats/) use them. See https://pinout.xyz/boards# for some examples (although I do acknowledge that some add-on boards don't use the ID EEPROM).

P.S. CSI = Camera, DSI = Display :wink: 

P.P.S. For more info about `config.txt` see https://www.raspberrypi.com/documentation/computers/config_txt.html and for more info about enabling i2c1 see https://www.raspberrypi.com/documentation/computers/configuration.html#part3.3

**Comment by ali1234** [comment]
I count 65 out of 205 unique boards that are marked as having an ID eeprom. Not all of these will have a corresponding device tree overlay for the firmware to load.

**Comment by ali1234** [comment]
There are also a couple missing such as TV HAT which I am fairly sure has an eeprom (I think all the RPiF HATs do). That seems to have been incorrectly marked as using the VC I2C pins instead.

In any case I recommend against specifically giving the instructions to take over this bus. Better to link to an explanation of why you shouldn't.

**Comment by lurch** [comment]
@Bra1nsen To get a bit more background-context here - do you actually **need** to use I2C0 on the HAT-ID pins, or were you just asking out of curiosity?

**Comment by Bra1nsen** [comment]
Very interesting conversion, especially the part with the csi part & thanks for the documentation link! some context: 

![setup](https://user-images.githubusercontent.com/58213050/222982437-9e1910ef-86a0-4052-977a-af8a528e138c.jpg)


Iam working on computer controlled cameras for sky observation, a new fan occupies the regular i2c pins, so I was considering using the alternate pins. But now it seems to me to be a bit[ cumbersome](https://forums.raspberrypi.com/viewtopic.php?t=304975)? Luckily there is still SPI for the temperaturesensor (bme280).

**Comment by lurch** [comment]
I2C allows you to have many devices connected to the same bus, provided that they each have a different address. (but that's something that I've never done myself)

**Comment by Bra1nsen** [comment]
yea true, I already did that with an i2c hub breakout :) but yea, the pins arent available so I why was interested in using the alternative gpio ones..

**Comment by lurch** [comment]
Based on the position of the Ethernet port in that photo, that looks like a Raspberry Pi 4, and those actually have many more I2C buses than earlier models https://elinux.org/RPi_BCM2711_GPIOs (which unfortunately pinout.xyz doesn't yet display #322 ).

**Comment by Bra1nsen** [comment]
thanks alot for that link lurch! 

in my case it would be nice to use gpio 6 and gpio 7
![image](https://user-images.githubusercontent.com/58213050/225148356-75bab1ec-7abd-443f-ba64-f044a9a101b5.png)

Can you explain why there are multiple gpios listed in one field? Would it also be possible to use gpio 8 and gpio 9 for example? 

Moreover do I have to change some internal pi settings for using these gpios or will it be sufficient telling the python script which gpios to use... anyway I will try myself. But yea you are a great help, thanks man!

**Comment by lurch** [comment]
> Can you explain why there are multiple gpios listed in one field?

Haha, I've actually edited that page myself [in the past](https://elinux.org/index.php?title=RPi_BCM2711_GPIOs&action=history), so yes I **can** explain why there are multiple GPIOs listed in one field... :rofl: 
If you look at the table mapping GPIOs to available functions:
![Screenshot from 2023-03-14 23-10-24](https://user-images.githubusercontent.com/476186/225162277-dc1185ca-4262-4e5b-8641-1448aeffeae5.png)
you can see that e.g. GPIO6 (alt-mode 5) is SDA4 and GPIO8 (alt-mode 5) is also SDA4, so that's why the second table says that SDA4 is available on both GPIO6 and GPIO8.

> Would it also be possible to use gpio 8 and gpio 9 for example?

Yes.

> Moreover do I have to change some internal pi settings for using these gpios

It's not something I've ever tried myself, but you _might_ need to change some [dtoverlay](https://www.raspberrypi.com/documentation/computers/configuration.html#part3.2) settings in [`config.txt`](https://www.raspberrypi.com/documentation/computers/config_txt.html) - see [here](https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/boot/dts/overlays/README) for a complete list, and I guess https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/boot/dts/overlays/README#L2167 is the option you're looking for? 
I believe you can also use https://github.com/RPi-Distro/raspi-gpio to see what "mode" your GPIO pins have been set to.

**Comment by Bra1nsen** [comment]
your help was absolutely professional. thanks for that!

```
sudo nano /boot/config.txt
dtoverlay=i2c-gpio,bus=3,i2c_gpio_sda=6,i2c_gpio_scl=7
sudo reboot
sudo i2cdetect -y 3
```
![image](https://user-images.githubusercontent.com/58213050/226645631-08c3e873-4a46-4b23-8609-13e714d9c670.png)
